"""Argon2id password hashing and password-policy validation.

AUTH-PASS-001..006 / `AUTH-001`..`AUTH-003`:

* Argon2id only - no custom hashing, no MD5/SHA/bcrypt substitute.
* A unique salt per hash, generated by argon2-cffi.
* Plaintext passwords are never persisted or returned.
* Passwords are never reversibly encrypted.
* Verification uses the library's constant-time `verify` API.
* Stored hashes can be re-hashed when parameters change.
"""

from __future__ import annotations

import unicodedata

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError
from argon2.low_level import Type

from app.auth.config import AuthConfig


class PasswordPolicyError(Exception):
    """Raised when a candidate password violates policy.

    The reason is safe to surface: it describes the policy, never the
    password.
    """

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


class PasswordHashing:
    """Argon2id hashing bound to the configured parameters."""

    __slots__ = ("_config", "_hasher")

    def __init__(self, config: AuthConfig) -> None:
        self._config = config
        self._hasher = PasswordHasher(
            time_cost=config.argon2_time_cost,
            memory_cost=config.argon2_memory_cost_kib,
            parallelism=config.argon2_parallelism,
            type=Type.ID,  # Argon2id, explicitly - not Argon2i or Argon2d.
        )

    def validate_policy(self, password: str) -> None:
        """Check a candidate password against policy.

        Length is measured in UTF-8 bytes because that is what the hashing
        layer actually consumes; a character count would let multi-byte input
        exceed the intended bound.
        """
        if not password:
            msg = "password must not be empty"
            raise PasswordPolicyError(msg)

        encoded_length = len(password.encode("utf-8"))
        if encoded_length < self._config.min_password_length:
            msg = f"password must be at least {self._config.min_password_length} bytes"
            raise PasswordPolicyError(msg)
        if encoded_length > self._config.max_password_length:
            msg = f"password must be at most {self._config.max_password_length} bytes"
            raise PasswordPolicyError(msg)

        # No character-composition rules: they reduce entropy in practice and
        # push users toward predictable substitutions. Length is the control.

    def hash(self, password: str) -> str:
        """Return an Argon2id encoded hash. The password is never truncated."""
        return self._hasher.hash(_normalize(password))

    def verify(self, stored_hash: str, password: str) -> bool:
        """Verify a password against a stored hash, in constant time.

        Returns False for a mismatch or an unreadable stored hash rather than
        raising, so callers cannot accidentally distinguish the two in an
        externally visible way.
        """
        try:
            self._hasher.verify(stored_hash, _normalize(password))
        except (VerifyMismatchError, VerificationError, InvalidHashError):
            return False
        return True

    def needs_rehash(self, stored_hash: str) -> bool:
        """Whether a stored hash was produced with outdated parameters."""
        try:
            return self._hasher.check_needs_rehash(stored_hash)
        except InvalidHashError:
            return True

    def dummy_verify(self) -> None:
        """Perform a throwaway verification.

        Called on the "no such account" path so that a login attempt for an
        unknown user still pays the Argon2 cost. Without this, response time
        alone would separate unknown accounts from wrong passwords.

        The mismatch it triggers is expected and swallowed - the point is the
        work, not the result.
        """
        try:
            self._hasher.verify(_DUMMY_HASH, "not-the-password")
        except (VerifyMismatchError, VerificationError, InvalidHashError):
            return


def _normalize(password: str) -> str:
    """Apply Unicode NFKC normalization.

    Without this, visually identical passwords entered on different platforms
    can produce different byte sequences and fail to verify.
    """
    return unicodedata.normalize("NFKC", password)


def _build_dummy_hash() -> str:
    """Build a fixed hash used only to equalize the unknown-account path."""
    hasher = PasswordHasher(time_cost=3, memory_cost=65536, parallelism=4, type=Type.ID)
    return hasher.hash("dummy-password-for-timing-equalization")


#: Not a credential: this hash exists only so `dummy_verify()` has something to
#: fail against. It is generated at import time and never matches user input.
_DUMMY_HASH = _build_dummy_hash()
